version: "3.3"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "8080:8080"
      - "4572:4572"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
